### ISSUE TITLE
adding work to cron

### ISSUE THREAD

**Issue by zzzloy777** [BitWeb/zf2-cron-module#14]
In configuration:
 'command'  => 'index.php application cron do-job',

From description :
"command"	 the php script command to be run

is that a console route ? is it possible to run a regular php script ?

**Comment by rammrain** [comment]
In the configurtation for ZF2 console route command is shown, but you can run any php script without command line arguments: `'command' => 'myScript.php'`

**Comment by zzzloy777** [comment]
thanks for your help !)
