### ISSUE TITLE
Configuration and manual issues

### ISSUE THREAD

**Issue by e-v-medvedev** [BitWeb/zf2-cron-module#15]
Can you say where cronModule section must be placed? in application.config.php or in cronModule.global.php or in module.config.php of my module? How i can add several jobs?

**Comment by rammrain** [comment]
Best would be to place it in cronModule.global.php or module.config.php of your module.

You can add multiple jobs by adding arrays to the jobs array in configuration.

**Comment by e-v-medvedev** [comment]
There is an error in your cronModule.config.php.dist. cronModule section missed.

**Comment by rammrain** [comment]
Fixed it.
