### ISSUE TITLE
move the controllers initializer closure to a function inside Module.php

### ISSUE THREAD

**Issue by dorongutman** [BitWeb/zf2-cron-module#9]
Config files should *NOT* have closures inside them, as it is impossible to cache them - if you'll try to use `'config_cache_enabled' => true` with this module enables you'll get an error or a blank page.

Please move the closure to the Module.php file.

Thanks.

**Comment by dorongutman** [comment]
@rammrain awesome, thanks!
If you could just tag a version now, that would be very helpful

**Comment by rammrain** [comment]
@dorongutman Done!
